-- AD_TextureLibrary: the pictures a texture offers (UI/AD_TextureOptions.lua's
-- picker), by group. Every picture is a game FileDataID, so it loads on any client;
-- a picture of your own is typed as an ID or a file path instead. A group with
-- glow = true is spell-effect art on black, made for the Glow blend: there its
-- black adds nothing and disappears, so picking one sets that blend.
local ADDON, NS = ...
local Options = NS.Options
if not Options then return end

Options.TEXTURE_LIBRARY = {
    { name = "Spell Alerts", pictures = {
        { id = 424570, name = "Spell Activation Overlay" },
        { id = 449486, name = "Arcane Missiles" },
        { id = 449487, name = "Blood Surge" },
        { id = 449488, name = "Brain Freeze" },
        { id = 449489, name = "Frozen Fingers" },
        { id = 449490, name = "Hot Streak" },
        { id = 449491, name = "Imp Empowerment" },
        { id = 449492, name = "Nightfall" },
        { id = 449493, name = "Sudden Death" },
        { id = 449494, name = "Sword and Board" },
        { id = 450913, name = "Art of War" },
        { id = 450914, name = "Eclipse Moon" },
        { id = 450915, name = "Eclipse Sun" },
        { id = 450916, name = "Focus Fire" },
        { id = 450917, name = "Generic Arc 1" },
        { id = 450918, name = "Generic Arc 2" },
        { id = 450919, name = "Generic Arc 3" },
        { id = 450920, name = "Generic Arc 4" },
        { id = 450921, name = "Generic Arc 5" },
        { id = 450922, name = "Generic Arc 6" },
        { id = 450923, name = "Generic Top 1" },
        { id = 450924, name = "Generic Top 2" },
        { id = 450925, name = "Grand Crusader" },
        { id = 450926, name = "Lock and Load" },
        { id = 450927, name = "Maelstrom Weapon" },
        { id = 450928, name = "Master Marksman" },
        { id = 450929, name = "Nature's Grace" },
        { id = 450930, name = "Rime" },
        { id = 450931, name = "Slice and Dice" },
        { id = 450932, name = "Sudden Doom" },
        { id = 450933, name = "Surge of Light" },
        { id = 457658, name = "Impact" },
        { id = 458740, name = "Killing Machine" },
        { id = 458741, name = "Molten Core" },
        { id = 459313, name = "Daybreak" },
        { id = 459314, name = "Hand of Light" },
        { id = 460830, name = "Backslash" },
        { id = 460831, name = "Fury of Stormrage" },
        { id = 461878, name = "Dark Transformation" },
        { id = 463452, name = "Shooting Stars" },
        { id = 467696, name = "Fulmination" },
        { id = 469752, name = "Serendipity" },
        { id = 510822, name = "Berserk" },
        { id = 510823, name = "Omen of Clarity (Feral)" },
        { id = 511104, name = "Blood Boil" },
        { id = 511105, name = "Necropolis" },
        { id = 511469, name = "Denounce" },
        { id = 592058, name = "Surge of Darkness" },
        { id = 603338, name = "Dark Tiger" },
        { id = 603339, name = "White Tiger" },
        { id = 623950, name = "Monk Ox" },
        { id = 623951, name = "Monk Serpent" },
        { id = 623952, name = "Monk Tiger" },
        { id = 627609, name = "Shadow of Death" },
        { id = 627610, name = "Ultimatum" },
        { id = 656728, name = "Shadow Word Insanity" },
        { id = 774420, name = "Tooth and Claw" },
        { id = 801266, name = "Backlash (Green)" },
        { id = 801267, name = "Imp Empowerment (Green)" },
        { id = 801268, name = "Molten Core (Green)" },
        { id = 898423, name = "Predatory Swiftness" },
        { id = 962497, name = "Raging Blow" },
        { id = 1001511, name = "Monk Blackout Kick" },
        { id = 1001512, name = "Monk Tiger Palm" },
        { id = 1027131, name = "Arcane Missiles 1" },
        { id = 1027132, name = "Arcane Missiles 2" },
        { id = 1027133, name = "Arcane Missiles 3" },
        { id = 1028091, name = "Monk Ox 2" },
        { id = 1028092, name = "Monk Ox 3" },
        { id = 1028136, name = "Maelstrom Weapon 1" },
        { id = 1028137, name = "Maelstrom Weapon 2" },
        { id = 1028138, name = "Maelstrom Weapon 3" },
        { id = 1028139, name = "Maelstrom Weapon 4" },
        { id = 1029138, name = "Thrill of the Hunt 1" },
        { id = 1029139, name = "Thrill of the Hunt 2" },
        { id = 1029140, name = "Thrill of the Hunt 3" },
        { id = 1030393, name = "Bandit's Guile" },
        { id = 1057288, name = "Echo of the Elements" },
        { id = 1518303, name = "Predatory Swiftness (Green)" },
        { id = 2851787, name = "Demonic Core" },
        { id = 2851788, name = "High Tide" },
        { id = 2888300, name = "Demonic Core Vertical" },
        { id = 4699056, name = "Essence Burst" },
        { id = 4699057, name = "Snapfire" },
        { id = 6160020, name = "Arcane Soul" },
        { id = 6160021, name = "Hyperthermia" },
    } },
    { name = "Icons", glow = true, pictures = {
        { id = 165558, name = "Paw" },
        { id = 165605, name = "Feathers" },
        { id = 165607, name = "Lion" },
        { id = 165608, name = "Cheetah" },
        { id = 165609, name = "Hawk" },
        { id = 165610, name = "Monkey" },
        { id = 165611, name = "Snake" },
        { id = 165612, name = "Wolf" },
        { id = 166036, name = "Rage" },
        { id = 166056, name = "Eye" },
        { id = 166058, name = "Eyes" },
        { id = 166125, name = "Fire" },
        { id = 166386, name = "Snowflake" },
        { id = 166418, name = "Inner Fire" },
        { id = 166423, name = "Intellect" },
        { id = 166606, name = "Leaf" },
        { id = 166662, name = "Shield" },
        { id = 166680, name = "Rampage" },
        { id = 166683, name = "Rapid Fire" },
        { id = 166706, name = "Reticle" },
        { id = 166948, name = "Spirit" },
        { id = 166954, name = "Bull" },
        { id = 166984, name = "Crossed Swords" },
        { id = 166989, name = "Stun Whirl" },
        { id = 240925, name = "Holy Ruin" },
        { id = 240961, name = "Crescent" },
        { id = 240972, name = "Poison Skull" },
        { id = 241049, name = "Star" },
    } },
    { name = "Runes", glow = true, pictures = {
        { id = 165630, name = "Ringed Aura Rune" },
        { id = 165631, name = "Square Aura Rune" },
        { id = 165633, name = "Tri-Circle Aura Rune" },
        { id = 165634, name = "Tri-Circle Ringed Aura Rune" },
        { id = 165635, name = "Spike-Ringed Aura Rune" },
        { id = 165638, name = "Small Tri-Circle Aura Rune" },
        { id = 165639, name = "Sliced Aura Rune" },
        { id = 165640, name = "Oblong Aura Rune" },
        { id = 165881, name = "Dark Summon" },
        { id = 165885, name = "Death Rune" },
        { id = 165922, name = "Demonic Summon" },
        { id = 165927, name = "Demon Rune 1" },
        { id = 165928, name = "Demon Rune 2" },
        { id = 165929, name = "Demon Rune 3" },
        { id = 166340, name = "Holy Rune" },
        { id = 166341, name = "Holy Cross Rune" },
        { id = 166748, name = "Filled Circular Rune" },
        { id = 166749, name = "Ringed Circular Rune" },
        { id = 166750, name = "Sparse Circular Rune" },
        { id = 166753, name = "Heavy BC Rune" },
        { id = 166754, name = "Light BC Rune" },
        { id = 166757, name = "Circular Frost Rune" },
        { id = 166979, name = "Star Rune" },
        { id = 241003, name = "Dual Blades" },
        { id = 241004, name = "Octagonal Skulls" },
        { id = 241005, name = "Dense Circular Rune" },
    } },
    { name = "Beams", glow = true, pictures = {
        { id = 167096, name = "Gold Chain" },
        { id = 167097, name = "Iron Chain" },
        { id = 167098, name = "Green Fire Beam" },
        { id = 167099, name = "Red Fire Beam" },
        { id = 167100, name = "Brown Smoke Beam" },
        { id = 167101, name = "Grey Smoke Beam" },
        { id = 167102, name = "Green Vine" },
        { id = 167103, name = "Red Vine" },
        { id = 167104, name = "Blue Water Beam" },
        { id = 167105, name = "Green Water Beam" },
        { id = 186185, name = "Purple Beam" },
        { id = 186186, name = "Red Beam" },
        { id = 186187, name = "Red Drops Beam" },
        { id = 186189, name = "Drain Mana Lightning" },
        { id = 186192, name = "Ethereal Ribbon" },
        { id = 186193, name = "Ghost Chain" },
        { id = 186194, name = "Purple Ghost Chain" },
        { id = 186195, name = "Heal Beam" },
        { id = 186198, name = "Lightning" },
        { id = 186201, name = "Red Lightning" },
        { id = 186202, name = "Mana Beam" },
        { id = 186205, name = "Mana Burn Beam" },
        { id = 186208, name = "Rope" },
        { id = 186211, name = "Shock Lightning" },
        { id = 186214, name = "Soul Beam" },
        { id = 241098, name = "Spirit Link Beam" },
        { id = 241099, name = "Summon Gargoyle Beam" },
        { id = 369749, name = "Straight Purple Beam" },
        { id = 369750, name = "Shadow Beam" },
    } },
    { name = "Sparks", glow = true, pictures = {
        { id = 130877, name = "Blizzard Spark" },
    } },
}

-- id -> name, for the picker's current value; id -> true for glow art
Options.TEXTURE_NAMES, Options.TEXTURE_GLOW = {}, {}
for _, g in ipairs(Options.TEXTURE_LIBRARY) do
    for _, p in ipairs(g.pictures) do
        Options.TEXTURE_NAMES[p.id] = p.name
        if g.glow then Options.TEXTURE_GLOW[p.id] = true end
    end
end

-- The game's own animated sheets: an atlas and its grid of frames. A client
-- shows the ones it has (the picker asks C_Texture); picking one switches
-- the picture to its animation.
Options.TEXTURE_SHEETS = {
    { atlas = "UI-HUD-ActionBar-Proc-Loop-Flipbook", name = "Spell alert loop", rows = 6, cols = 5, frames = 30, time = 1 },
    { atlas = "UI-HUD-ActionBar-Proc-Start-Flipbook", name = "Spell alert burst", rows = 6, cols = 5, frames = 30, time = 0.7 },
    { atlas = "UI-HUD-ActionBar-GCD-Flipbook", name = "Cooldown flash", rows = 11, cols = 2, frames = 22, time = 0.75 },
    { atlas = "VisualAlert_Ants_Flipbook", name = "Marching ants", rows = 6, cols = 5, frames = 30, time = 1 },
    { atlas = "rotationhelper_ants_flipbook", name = "Marching ants, blue", rows = 6, cols = 5, frames = 30, time = 1 },
    { atlas = "groupfinder-eye-flipbook-searching", name = "Searching eye", rows = 8, cols = 11, frames = 80, time = 2 },
    { atlas = "groupfinder-eye-flipbook-found-loop", name = "Watching eye", rows = 4, cols = 11, frames = 41, time = 1.5 },
    { atlas = "UI-HUD-UnitFrame-Player-Rest-Flipbook", name = "Resting", rows = 7, cols = 6, frames = 42, time = 1.5 },
    { atlas = "UF-SoulShards-Flipbook-Soul", name = "Soul wisp", rows = 3, cols = 7, frames = 18, time = 0.6 },
    { atlas = "Fyrakk_Flame_FX", name = "Flame", rows = 8, cols = 6, frames = 44, time = 1.33 },
    { atlas = "UF-Arcane-ShockFX", name = "Arcane shock", rows = 5, cols = 6, frames = 28, time = 1 },
    { atlas = "UF-HolyPower-DepleteRune1", name = "Holy rune burst", rows = 5, cols = 6, frames = 26, time = 0.87 },
    { atlas = "UF-DKRunes-BloodDeplete", name = "Blood rune burst", rows = 4, cols = 6, frames = 23, time = 1 },
    { atlas = "UF-DruidCP-Slash", name = "Claw slash", rows = 3, cols = 8, frames = 20, time = 1 },
    { atlas = "uf-roguecp-slash-red", name = "Red slash", rows = 3, cols = 6, frames = 17, time = 0.57 },
    { atlas = "uf-roguecp-slash-blue", name = "Blue slash", rows = 3, cols = 6, frames = 17, time = 0.57 },
    { atlas = "uf-chi-windfx", name = "Wind swirl", rows = 3, cols = 6, frames = 17, time = 0.57 },
    { atlas = "lootroll-animdiceglow", name = "Dice glow", rows = 10, cols = 5, frames = 50, time = 1.67 },
    { atlas = "rolls100-sparks1-anim", name = "Sparks", rows = 5, cols = 6, frames = 30, time = 1 },
    { atlas = "rolls100-sparks2-anim", name = "Sparks 2", rows = 6, cols = 5, frames = 30, time = 0.97 },
    { atlas = "shop-loading-sparkle-flipbook", name = "Sparkle", rows = 5, cols = 4, frames = 20, time = 0.8 },
    { atlas = "activities-complete-diamond-sparkles", name = "Diamond sparkles", rows = 2, cols = 7, frames = 14, time = 0.5 },
    { atlas = "housing-item-toast-sparkles-flipbook", name = "Sparkle shower", rows = 10, cols = 5, frames = 50, time = 3 },
    { atlas = "hearthsteel-icon-lg-fx-flipbook", name = "Shimmer", rows = 10, cols = 6, frames = 60, time = 1.5, glow = true },
    { atlas = "perks-frost-FX", name = "Frost", rows = 3, cols = 5, frames = 13, time = 1 },
    { atlas = "timerunning-fx-cornerswoop-flipbook", name = "Corner swoop", rows = 7, cols = 9, frames = 63, time = 2, glow = true },
}
-- atlas -> its sheet
Options.TEXTURE_SHEET_OF = {}
for _, s in ipairs(Options.TEXTURE_SHEETS) do Options.TEXTURE_SHEET_OF[s.atlas] = s end
